# Generated by Django 5.0.7 on 2024-10-26 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='letterId',
            field=models.CharField(default=datetime.datetime(2024, 10, 26, 16, 8, 19, 134545, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='genes',
            field=models.CharField(max_length=32),
        ),
    ]
