# Generated by Django 5.0.7 on 2024-11-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameui', '0002_pet_letterid_alter_pet_genes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egg',
            name='color',
        ),
        migrations.AddField(
            model_name='egg',
            name='color1',
            field=models.CharField(default='ffffff', max_length=6),
        ),
        migrations.AddField(
            model_name='egg',
            name='color2',
            field=models.CharField(default='ffffff', max_length=6),
        ),
        migrations.AddField(
            model_name='egg',
            name='lastChecked',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='egg',
            name='untilHatch',
            field=models.IntegerField(default=3),
        ),
    ]
