# Generated by Django 5.0.7 on 2024-11-04 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameui', '0003_remove_egg_color_egg_color1_egg_color2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='egg',
            name='lastChecked',
        ),
        migrations.RemoveField(
            model_name='egg',
            name='untilHatch',
        ),
        migrations.AddField(
            model_name='egg',
            name='hatchDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 4, 19, 49, 50, 538602)),
        ),
    ]
