# Generated by Django 5.1.3 on 2024-11-15 11:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameui', '0004_remove_egg_lastchecked_remove_egg_untilhatch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='hatchDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 13, 54, 8, 235150)),
        ),
    ]
