# Generated by Django 5.1.3 on 2024-11-17 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameui', '0008_alter_egg_hatchdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='egg',
            name='determined_gender',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='egg',
            name='gender_determined_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='egg',
            name='hatchDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 13, 29, 9, 276571)),
        ),
    ]
