# Generated by Django 5.1.3 on 2024-11-17 11:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameui', '0010_alter_egg_hatchdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egg',
            name='hatchDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 20, 13, 37, 41, 545005)),
        ),
    ]
